### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by vince62s** [vedantroy/gpu_kernels#1]
Hi,

I looked at your code and it is very similar to the GPTQ triton implementation

However according to this post here: https://github.com/PanQiWei/AutoGPTQ/issues/350
the performance of the triton kernel is slower than the cuda one.

did you test it the same way ?

**Comment by vedantroy** [comment]
I'm testing against the CUDA kernels in the awq github repository, which are presumably different from the gptq-triton CUDA kernels. The CUDA kernels in the awq repository aren't using CUTLASS / etc., so it is unsurprising that they are slower than a Triton implementation.
